// Umfangreiche Genre-Liste für die Profil-Auswahl.
// Die Namen entsprechen gängigen Spotify-Genres und funktionieren
// direkt als Seeds für die Genre-Suche in der Empfehlungs-Engine.
export const ALL_GENRES: string[] = [
  "acid house",
  "acid jazz",
  "acoustic",
  "afrobeat",
  "afro house",
  "alternative",
  "alternative metal",
  "alternative rock",
  "ambient",
  "americana",
  "art pop",
  "art rock",
  "avant-garde",
  "balearic",
  "baroque pop",
  "bass music",
  "bebop",
  "bedroom pop",
  "berlin techno",
  "big band",
  "black metal",
  "blackgaze",
  "bluegrass",
  "blues",
  "blues rock",
  "bossa nova",
  "breakbeat",
  "breakcore",
  "britpop",
  "chamber pop",
  "chanson",
  "chillhop",
  "chillwave",
  "city pop",
  "classical",
  "coldwave",
  "contemporary jazz",
  "country",
  "dancehall",
  "dark ambient",
  "dark jazz",
  "darkwave",
  "death metal",
  "deep house",
  "disco",
  "doom metal",
  "downtempo",
  "dream pop",
  "drill",
  "drone",
  "drum and bass",
  "dub",
  "dub techno",
  "dubstep",
  "electro",
  "electroclash",
  "electronic",
  "emo",
  "ethereal wave",
  "experimental",
  "film score",
  "flamenco",
  "folk",
  "folktronica",
  "footwork",
  "free jazz",
  "french house",
  "funk",
  "future garage",
  "garage rock",
  "glitch",
  "gospel",
  "gothic rock",
  "grime",
  "grunge",
  "hard bop",
  "hardcore",
  "hardstyle",
  "heavy metal",
  "hip hop",
  "house",
  "hyperpop",
  "idm",
  "indie folk",
  "indie pop",
  "indie rock",
  "industrial",
  "industrial techno",
  "instrumental",
  "italo disco",
  "j-pop",
  "jazz",
  "jazz fusion",
  "jungle",
  "k-pop",
  "krautrock",
  "latin",
  "leftfield",
  "lo-fi",
  "lounge",
  "math rock",
  "melodic house",
  "melodic techno",
  "metalcore",
  "microhouse",
  "minimal techno",
  "minimal wave",
  "modern classical",
  "motown",
  "neo-classical",
  "neo-psychedelia",
  "neo-soul",
  "new age",
  "new wave",
  "noise",
  "noise rock",
  "nu jazz",
  "nu metal",
  "opera",
  "orchestral",
  "phonk",
  "piano",
  "pop",
  "post-bop",
  "post-hardcore",
  "post-punk",
  "post-rock",
  "power pop",
  "progressive house",
  "progressive metal",
  "progressive rock",
  "psychedelic rock",
  "psytrance",
  "punk",
  "r&b",
  "rap",
  "reggae",
  "reggaeton",
  "rock",
  "rockabilly",
  "roots reggae",
  "salsa",
  "samba",
  "shoegaze",
  "singer-songwriter",
  "ska",
  "slowcore",
  "sludge metal",
  "soul",
  "soundtrack",
  "space rock",
  "spoken word",
  "stoner rock",
  "surf rock",
  "swing",
  "synth-pop",
  "synthwave",
  "tech house",
  "techno",
  "trance",
  "trap",
  "trip hop",
  "uk garage",
  "vaporwave",
  "witch house",
  "world music",
];
